# MatchBot configuration file
# Discord settings
enabled: true # Enable Discord bot?
token: "" # Discord bot token
server: "" # ID of Discord server
match-channel: "" # ID of channel where match embeds will be sent

# Minecraft settings
server-name: "" # Name of the server (useful for networks)

# Image URL to display in the embed's thumbnail if a map image is not found
# Example: https://raw.githubusercontent.com/TBG1000/MapImages/main/map_image_not_found.png
map-image-not-found: ""